### ISSUE TITLE
Setting 3 and 4

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mwe-pytest-in-package#2]
I basically try to replicate a setting from https://pytest.org/latest/goodpractises.html#choosing-a-test-layout-import-rules where tests are stored in a child (setting 3) or sister (setting 4) fodler relative to the script. 

I have not done `pip install -e` or any other command to register the package, that can be the reason. I do not understand what happens then and want stay wasy from it, if I can. 

My intended result is to store tests in child or  sister forlder and to be able to import a function from code3.py module with least extra settings (package setup, pythonpath, etc). 

Need some changes in these lines of code and or some other action:
- https://github.com/epogrebnyak/mwe-pytest-in-package/blob/master/setting_3/test/test_in_child_folder.py#L1-L2
- https://github.com/epogrebnyak/mwe-pytest-in-package/blob/master/setting_4/test/test_in_sister_folder.py#L1-L2

Also may help adding **init**.py to test folder, even though this is not encouraged in https://pytest.org/latest/goodpractises.html#choosing-a-test-layout-import-rules

**Comment by epogrebnyak** [comment]
setting 3 is now reachable by py.test (I can run it both from setting_3 and setting_3/test folders). 

remaining question: how can I run test/test_in_child_folder.py with python? 
to me all below fail:

```
>python test/test_in_child_folder.py

Traceback (most recent call last):
  File "test\test_in_child_folder.py", line 3, in <module>
    from ..code3 import foo
SystemError: Parent module '' not loaded, cannot perform relative import

> python -m test/test_in_child_folder.py
C:\Users\Евгений\Anaconda3\python.exe: Error while finding spec for 'test/test_in_child_folder.py' (<class 'ImportError'>: No module named 'test/test_in_child_folder')
```

however py.test picks this file fine:

```
> py.test test\test_in_child_folder.py
============================= test session starts =============================
platform win32 -- Python 3.5.0, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: C:\Users\Евгений\Documents\GitHub\mwe-pytest-in-package\setting_3\test, inifile:
collected 1 items

test\test_in_child_folder.py .

========================== 1 passed in 0.02 seconds ===========================
```

**Comment by dniku** [comment]
This is the same problem as with `setting_1`: `py.test` injects its own import loader in `sys.meta_path`, which is why running the script under `py.test` works while under CPython it doesn't.

The recommendations from `py.test` website are for those people who write code which is supposed to be installed system-wide. This does not restrict to libraries: see [this](https://github.com/deluge-torrent/deluge/tree/develop/deluge/tests), for example (Deluge doesn't use `py.test`, but it performs absolute imports in the tests).

Since we don't want to install the code we're writing, we are on our own at finding the code we want to test. The simplest solution would be to place everything in something like `tests.py` and leave that file in the root directory. That is what [`six`](https://bitbucket.org/gutworth/six/src) does. Another solution would be to add the path to the code that we wish to import to `sys.path`. So, something like this:

``` python
import sys
sys.path.append('..')
import code3
```

This will only work if we guarantee two things: the tests should always be in the same directory relative to code and they should be executed from the directory they're in. We can also add a path to the folder which is the parent folder of the script, by replacing `'..'` with `os.path.dirname(os.path.dirname(os.path.realpath(__file__))))`. This will solve the second issue.

I would suggest placing tests in a single file. As far as I understand, we don't intend to grow this project beyond a couple thousand lines of code. Do we really need to overengineer it?

**Comment by epogrebnyak** [comment]
Main intent was/is to be able to put groups of python files to own folders
(converter, parser, selector), and also put tests somewhere away (e.g.
child folder, sister folder).

My main problem is that I have a hard time working with modules inside
packages, this is not just a question where to put tests at, but also how
to structure code itself.

I will make a commit to rosstat folder to describe the intents.

Many thanks for your thoughtful comment.
4 дек. 2015 г. 21:20 пользователь "Pastafarianist" notifications@github.com
написал:

**Comment by gabrielelanaro** [comment]
> remaining question: how can I run test/test_in_child_folder.py with python?

The error pops up because on how relative import works. Basically when there's a relative import `..code3`, python looks at the `__package__` variable. When you call py-test this variable is:

```
setting_3.test
```

at this point you can see that if you go two "dot levels" up you are at the package `setting_3` and you can import the code.

When you call like this: `test/test_in_child_folder.py` the `__package__` variable is `None` so python doesn't know how to go "up". The best way to call it from python would be to go outside setting_3 and running

```
python -m setting_3.test.test_in_child_folder
```

This allows python to know what is the package structure (through the `__package__`) variable.

What I usually do in my projects (most projects adopt this convention) is the following:

```
/root/
    mypackage/
        __init__.py
        hello.py
        world/
           __init__.py
           banana.py

    tests/
       __init__.py
       test_hello.py
       test_world.py
```

And the test files will use absolute imports:

```
# file test_hello.py

import mypackage.hello
```

And the package files will use relative imports

```
# file banana.py
from .. import hello
```

**Comment by epogrebnyak** [comment]
Many thanks! python -m setting_3.test.test_in_child_folder is especially useful hint

**Comment by epogrebnyak** [comment]
3ba066345eee715780f5aef101c4ec2c33166755
